// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Дата с опциональными компонентами.
 *
 * Используется для дат выхода аниме/манги, дат рождения людей и т.д.
 */
export type Date = { 
/**
 * Год (например, 2024).
 */
year: number | null, 
/**
 * Месяц (1-12).
 */
month: number | null, 
/**
 * День месяца (1-31).
 */
day: number | null, 
/**
 * Полная дата в формате строки (ISO 8601 или другой формат API).
 */
date: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Постер (изображение) для аниме, манги, персонажа или человека.
 *
 * Содержит ссылки на изображения разных размеров.
 */
export type Poster = { 
/**
 * ID постера в системе Shikimori.
 */
id: bigint | null, 
/**
 * URL оригинального изображения (полный размер).
 */
originalUrl: string | null, 
/**
 * URL основного изображения (оптимизированный размер).
 */
mainUrl: string | null, 
/**
 * URL превью-изображения.
 */
previewUrl: string | null, 
/**
 * URL изображения 96x96.
 */
x96Url: string | null, 
/**
 * URL изображения 48x48.
 */
x48Url: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Жанр аниме или манги.
 */
export type Genre = { 
/**
 * ID жанра в системе Shikimori.
 */
id: bigint, 
/**
 * Название жанра на английском.
 */
name: string, 
/**
 * Название жанра на русском.
 */
russian: string | null, 
/**
 * Тип жанра (например, "anime", "manga").
 */
kind: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Студия аниме.
 */
export type Studio = { 
/**
 * ID студии в системе Shikimori.
 */
id: bigint, 
/**
 * Название студии.
 */
name: string, 
/**
 * URL логотипа студии.
 */
image_url: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Издательство манги.
 */
export type Publisher = { 
/**
 * ID издательства в системе Shikimori.
 */
id: bigint, 
/**
 * Название издательства.
 */
name: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalLink = { id: bigint | null, kind: string, url: string, createdAt: string | null, updatedAt: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Poster } from "./Poster";

export type Person = { id: bigint, name: string, russian: string | null, poster: Poster | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Person } from "./Person";

export type PersonRole = { id: bigint, rolesRu: Array<string> | null, rolesEn: Array<string> | null, person: Person, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Poster } from "./Poster";

export type Character = { id: bigint, name: string, russian: string | null, poster: Poster | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Anime } from "./Anime";
import type { Character } from "./Character";
import type { Manga } from "./Manga";

export type CharacterRole = { id: bigint, rolesRu: Array<string> | null, rolesEn: Array<string> | null, character: Character | null, anime: Anime | null, manga: Manga | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Poster } from "./Poster";

export type RelatedAnime = { id: bigint | null, name: string | null, russian: string | null, poster: Poster | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Poster } from "./Poster";

export type RelatedManga = { id: bigint | null, name: string | null, russian: string | null, poster: Poster | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SimilarAnimeImage } from "./SimilarAnimeImage";

/**
 * Похожее аниме из REST API Shikimori (/api/animes/{id}/similar)
 */
export type SimilarAnime = { id: bigint | null, name: string | null, russian: string | null, kind: string | null, status: string | null, image: SimilarAnimeImage | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Изображение для похожего аниме из REST API
 */
export type SimilarAnimeImage = { original: string | null, preview: string | null, x48: string | null, x96: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RelatedAnime } from "./RelatedAnime";
import type { RelatedManga } from "./RelatedManga";

export type Related = { id: bigint, anime: RelatedAnime | null, manga: RelatedManga | null, relationKind: string, relationText: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Video = { id: bigint, url: string | null, name: string | null, kind: string | null, playerUrl: string | null, imageUrl: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Screenshot = { id: bigint, originalUrl: string | null, x166Url: string | null, x332Url: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScoreStat = { score: number, count: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StatusStat = { status: string, count: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharacterRole } from "./CharacterRole";
import type { Date } from "./Date";
import type { ExternalLink } from "./ExternalLink";
import type { Genre } from "./Genre";
import type { PersonRole } from "./PersonRole";
import type { Poster } from "./Poster";
import type { Related } from "./Related";
import type { ScoreStat } from "./ScoreStat";
import type { Screenshot } from "./Screenshot";
import type { StatusStat } from "./StatusStat";
import type { Studio } from "./Studio";
import type { Video } from "./Video";

/**
 * Полная информация об аниме.
 *
 * Содержит все доступные данные об аниме: названия, оценки, студии, жанры,
 * персонажи, связанные произведения, видео, скриншоты и многое другое.
 *
 * # Примеры
 *
 * ```no_run
 * use shikicrate::{ShikicrateClient, queries::*};
 *
 * # async fn example() -> Result<(), Box<dyn std::error::Error>> {
 * let client = ShikicrateClient::new()?;
 * let animes = client.animes(AnimeSearchParams {
 *     search: Some("naruto".to_string()),
 *     limit: Some(1),
 *     kind: None,
 *     page: None,
 * }).await?;
 *
 * if let Some(anime) = animes.first() {
 *     println!("Название: {}", anime.name);
 *     if let Some(russian) = &anime.russian {
 *         println!("Русское название: {}", russian);
 *     }
 *     if let Some(score) = anime.score {
 *         println!("Оценка: {:.2}", score);
 *     }
 * }
 * # Ok(())
 * # }
 * ```
 */
export type Anime = { 
/**
 * ID аниме в системе Shikimori.
 */
id: bigint, 
/**
 * ID аниме в MyAnimeList (если есть).
 */
mal_id: bigint | null, 
/**
 * Основное название аниме.
 */
name: string, 
/**
 * Русское название (если есть).
 */
russian: string | null, 
/**
 * Лицензионное русское название (если есть).
 */
licenseNameRu: string | null, 
/**
 * Английское название (если есть).
 */
english: string | null, 
/**
 * Японское название (если есть).
 */
japanese: string | null, 
/**
 * Синонимы и альтернативные названия.
 */
synonyms: Array<string> | null, 
/**
 * Тип аниме: `"tv"`, `"movie"`, `"ova"`, `"ona"`, `"special"`, `"music"`.
 */
kind: string | null, 
/**
 * Возрастной рейтинг: `"g"`, `"pg"`, `"pg_13"`, `"r"`, `"r_plus"`, `"rx"`.
 */
rating: string | null, 
/**
 * Средняя оценка пользователей (0.0 - 10.0).
 */
score: number | null, 
/**
 * Статус: `"anons"`, `"ongoing"`, `"released"`.
 */
status: string | null, 
/**
 * Общее количество эпизодов (планируемое).
 */
episodes: number | null, 
/**
 * Количество вышедших эпизодов.
 */
episodesAired: number | null, 
/**
 * Длительность одного эпизода в минутах.
 */
duration: number | null, 
/**
 * Дата начала показа.
 */
airedOn: Date | null, 
/**
 * Дата релиза.
 */
releasedOn: Date | null, 
/**
 * URL страницы аниме на Shikimori.
 */
url: string | null, 
/**
 * Сезон выхода: `"winter"`, `"spring"`, `"summer"`, `"fall"`.
 */
season: string | null, 
/**
 * Постер аниме.
 */
poster: Poster | null, 
/**
 * Список фансабберов (если есть).
 */
fansubbers: Array<string> | null, 
/**
 * Список фандабберов (если есть).
 */
fandubbers: Array<string> | null, 
/**
 * Список лицензиатов.
 */
licensors: Array<string> | null, 
/**
 * Дата создания записи в системе.
 */
createdAt: string | null, 
/**
 * Дата последнего обновления.
 */
updatedAt: string | null, 
/**
 * Дата выхода следующего эпизода (для онгоингов).
 */
nextEpisodeAt: string | null, 
/**
 * Флаг цензуры.
 */
isCensored: boolean | null, 
/**
 * Список жанров.
 */
genres: Array<Genre> | null, 
/**
 * Список студий.
 */
studios: Array<Studio> | null, 
/**
 * Внешние ссылки (официальные сайты, соцсети и т.д.).
 */
externalLinks: Array<ExternalLink> | null, 
/**
 * Роли людей (сейю, режиссеры, композиторы и т.д.).
 */
personRoles: Array<PersonRole> | null, 
/**
 * Роли персонажей.
 */
characterRoles: Array<CharacterRole> | null, 
/**
 * Связанные произведения (сиквелы, приквелы, спин-оффы и т.д.).
 */
related: Array<Related> | null, 
/**
 * Видео (трейлеры, опенинги, эндинги).
 */
videos: Array<Video> | null, 
/**
 * Скриншоты из аниме.
 */
screenshots: Array<Screenshot> | null, 
/**
 * Статистика оценок (распределение по баллам).
 */
scoresStats: Array<ScoreStat> | null, 
/**
 * Статистика статусов просмотра (сколько пользователей смотрит, дропнуло и т.д.).
 */
statusesStats: Array<StatusStat> | null, 
/**
 * Описание аниме (текст).
 */
description: string | null, 
/**
 * Описание аниме (HTML).
 */
descriptionHtml: string | null, 
/**
 * Источник описания.
 */
descriptionSource: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharacterRole } from "./CharacterRole";
import type { Date } from "./Date";
import type { ExternalLink } from "./ExternalLink";
import type { Genre } from "./Genre";
import type { PersonRole } from "./PersonRole";
import type { Poster } from "./Poster";
import type { Publisher } from "./Publisher";
import type { Related } from "./Related";
import type { ScoreStat } from "./ScoreStat";
import type { StatusStat } from "./StatusStat";

/**
 * Полная информация о манге.
 *
 * Содержит все доступные данные о манге: названия, оценки, издательства, жанры,
 * персонажей, связанные произведения и многое другое.
 *
 * Структура похожа на `Anime`, но содержит специфичные для манги поля
 * (например, `volumes`, `chapters`, `publishers` вместо `studios`).
 */
export type Manga = { 
/**
 * ID манги в системе Shikimori.
 */
id: bigint, 
/**
 * ID манги в MyAnimeList (если есть).
 */
mal_id: bigint | null, 
/**
 * Основное название манги.
 */
name: string, 
/**
 * Русское название (если есть).
 */
russian: string | null, 
/**
 * Лицензионное русское название (если есть).
 */
licenseNameRu: string | null, 
/**
 * Английское название (если есть).
 */
english: string | null, 
/**
 * Японское название (если есть).
 */
japanese: string | null, 
/**
 * Синонимы и альтернативные названия.
 */
synonyms: Array<string> | null, 
/**
 * Тип манги: `"manga"`, `"novel"`, `"one_shot"`, `"doujin"`, `"manhwa"`, `"manhua"`.
 */
kind: string | null, 
/**
 * Средняя оценка пользователей (0.0 - 10.0).
 */
score: number | null, 
/**
 * Статус: `"anons"`, `"ongoing"`, `"released"`.
 */
status: string | null, 
/**
 * Количество томов (планируемое).
 */
volumes: number | null, 
/**
 * Количество глав (планируемое).
 */
chapters: number | null, 
/**
 * Дата начала публикации.
 */
airedOn: Date | null, 
/**
 * Дата релиза.
 */
releasedOn: Date | null, 
/**
 * URL страницы манги на Shikimori.
 */
url: string | null, 
/**
 * Постер манги.
 */
poster: Poster | null, 
/**
 * Список лицензиатов.
 */
licensors: Array<string> | null, 
/**
 * Дата создания записи в системе.
 */
createdAt: string | null, 
/**
 * Дата последнего обновления.
 */
updatedAt: string | null, 
/**
 * Флаг цензуры.
 */
isCensored: boolean | null, 
/**
 * Список жанров.
 */
genres: Array<Genre> | null, 
/**
 * Список издательств.
 */
publishers: Array<Publisher> | null, 
/**
 * Внешние ссылки (официальные сайты, соцсети и т.д.).
 */
externalLinks: Array<ExternalLink> | null, 
/**
 * Роли людей (авторы, иллюстраторы и т.д.).
 */
personRoles: Array<PersonRole> | null, 
/**
 * Роли персонажей.
 */
characterRoles: Array<CharacterRole> | null, 
/**
 * Связанные произведения (сиквелы, приквелы, спин-оффы и т.д.).
 */
related: Array<Related> | null, 
/**
 * Статистика оценок (распределение по баллам).
 */
scoresStats: Array<ScoreStat> | null, 
/**
 * Статистика статусов чтения (сколько пользователей читает, дропнуло и т.д.).
 */
statusesStats: Array<StatusStat> | null, 
/**
 * Описание манги (текст).
 */
description: string | null, 
/**
 * Описание манги (HTML).
 */
descriptionHtml: string | null, 
/**
 * Источник описания.
 */
descriptionSource: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Poster } from "./Poster";

/**
 * Полная информация о персонаже.
 *
 * Содержит все доступные данные о персонаже: имена, описания, постеры,
 * флаги участия в аниме/манге/ранобэ.
 */
export type CharacterFull = { 
/**
 * ID персонажа в системе Shikimori.
 */
id: bigint, 
/**
 * ID персонажа в MyAnimeList (если есть).
 */
mal_id: bigint | null, 
/**
 * Основное имя персонажа.
 */
name: string, 
/**
 * Русское имя (если есть).
 */
russian: string | null, 
/**
 * Японское имя (если есть).
 */
japanese: string | null, 
/**
 * Синонимы и альтернативные имена.
 */
synonyms: Array<string> | null, 
/**
 * URL страницы персонажа на Shikimori.
 */
url: string | null, 
/**
 * Дата создания записи в системе.
 */
createdAt: string | null, 
/**
 * Дата последнего обновления.
 */
updatedAt: string | null, 
/**
 * Флаг участия в аниме.
 */
isAnime: boolean | null, 
/**
 * Флаг участия в манге.
 */
isManga: boolean | null, 
/**
 * Флаг участия в ранобэ.
 */
isRanobe: boolean | null, 
/**
 * Постер персонажа.
 */
poster: Poster | null, 
/**
 * Описание персонажа (текст).
 */
description: string | null, 
/**
 * Описание персонажа (HTML).
 */
descriptionHtml: string | null, 
/**
 * Источник описания.
 */
descriptionSource: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Date } from "./Date";
import type { Poster } from "./Poster";

/**
 * Полная информация о человеке (сейю, мангака, продюсер и т.д.).
 *
 * Содержит все доступные данные о человеке: имена, даты рождения/смерти,
 * роли (сейю, мангака, продюсер), постеры и другую информацию.
 */
export type PersonFull = { 
/**
 * ID человека в системе Shikimori.
 */
id: bigint, 
/**
 * ID человека в MyAnimeList (если есть).
 */
mal_id: bigint | null, 
/**
 * Основное имя человека.
 */
name: string, 
/**
 * Русское имя (если есть).
 */
russian: string | null, 
/**
 * Японское имя (если есть).
 */
japanese: string | null, 
/**
 * Синонимы и альтернативные имена.
 */
synonyms: Array<string> | null, 
/**
 * URL страницы человека на Shikimori.
 */
url: string | null, 
/**
 * Флаг: является ли сейю.
 */
isSeyu: boolean | null, 
/**
 * Флаг: является ли мангакой.
 */
isMangaka: boolean | null, 
/**
 * Флаг: является ли продюсером.
 */
isProducer: boolean | null, 
/**
 * Официальный сайт человека (если есть).
 */
website: string | null, 
/**
 * Дата создания записи в системе.
 */
createdAt: string | null, 
/**
 * Дата последнего обновления.
 */
updatedAt: string | null, 
/**
 * Дата рождения.
 */
birthOn: Date | null, 
/**
 * Дата смерти (если есть).
 */
deceasedOn: Date | null, 
/**
 * Постер человека.
 */
poster: Poster | null, };